imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ AdminBundle ]
    bundles:        [ SalesBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
         main_js:
            inputs: 
              - '@AdminBundle/Resources/public/js/jquery-1.10.2.min.js'
              - '@AdminBundle/Resources/public/js/jquery-migrate-1.2.1.min.js'
              - '@AdminBundle/Resources/public/js/jquery-ui.js'
              - '@AdminBundle/Resources/public/js/bootstrap.min.js'
              - '@AdminBundle/Resources/public/js/bootstrap-hover-dropdown.js'
              - '@AdminBundle/Resources/public/js/html5shiv.js'
              - '@AdminBundle/Resources/public/js/respond.min.js'
              - '@AdminBundle/Resources/public/js/jquery.metisMenu.js'
              - '@AdminBundle/Resources/public/js/jquery.slimscroll.js'
              - '@AdminBundle/Resources/public/js/jquery.cookie.js'
              - '@AdminBundle/Resources/public/js/icheck.min.js'
              - '@AdminBundle/Resources/public/js/custom.min.js'
              - '@AdminBundle/Resources/public/js/jquery.news-ticker.js'
              - '@AdminBundle/Resources/public/js/jquery.menu.js'
              - '@AdminBundle/Resources/public/js/pace.min.js'
              - '@AdminBundle/Resources/public/js/holder.js'
              - '@AdminBundle/Resources/public/js/responsive-tabs.js'
              - '@AdminBundle/Resources/public/js/jquery.flot.js'
              - '@AdminBundle/Resources/public/js/jquery.flot.categories.js'
              - '@AdminBundle/Resources/public/js/jquery.flot.pie.js'
              - '@AdminBundle/Resources/public/js/jquery.flot.tooltip.js'
              - '@AdminBundle/Resources/public/js/jquery.flot.resize.js'
              - '@AdminBundle/Resources/public/js/jquery.flot.fillbetween.js'
              - '@AdminBundle/Resources/public/js/jquery.flot.stack.js'
              - '@AdminBundle/Resources/public/js/jquery.flot.spline.js'
              - '@AdminBundle/Resources/public/js/zabuto_calendar.min.js'
              - '@AdminBundle/Resources/public/js/index.js' 
         chart_js:
            inputs:
              - '@AdminBundle/Resources/public/js/highcharts.js'
              - '@AdminBundle/Resources/public/js/data.js'
              - '@AdminBundle/Resources/public/js/drilldown.js'
              - '@AdminBundle/Resources/public/js/exporting.js'
              - '@AdminBundle/Resources/public/js/highcharts-more.js'
              - '@AdminBundle/Resources/public/js/charts-highchart-pie.js'
              - '@AdminBundle/Resources/public/js/charts-highchart-more.js'
         jplist_js:
            inputs:
              - '@AdminBundle/Resources/public/js/modernizr.min.js'
              - '@AdminBundle/Resources/public/js/jplist.min.js'
              - '@AdminBundle/Resources/public/js/jplist.js'
              
         core_js:
            inputs:
              - '@AdminBundle/Resources/public/js/main.js'
# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
