admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

sales:
    resource: "@SalesBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
