sales_homepage:
    path:     /hello/{name}
    defaults: { _controller: SalesBundle:Default:index }
sales_welcome:
    path:     /welcome/{name}
    defaults: { _controller: SalesBundle:Default:welcome }